linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - golint # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - varnamelen
    - wrapcheck
