services:

  redis:
    image: redis:${REDIS_VERSION:-7}
    ports:
      - 6379:6379
    networks:
      - testnet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

  app:
    build:
      context: .
      target: release
    ports:
      - "8080:8080"
    networks:
      - testnet
    environment:
      REDIS_URL: redis:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "curl", "-f", "http://localhost:8080/status" ]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 3s

  int-test:
    build:
      context: .
      target: tester
    container_name: int-test
    networks:
      - testnet
    environment:
      REDIS_URL: redis:6379
    depends_on:
      redis:
        condition: service_healthy

networks:
  testnet:
    name: testnet
