version: 2.1
orbs:
  codecov: codecov/codecov@3

executors:
  go:
    docker:
      - image: cimg/go:1.18
    resource_class: small

jobs:
  lint:
    executor: go
    steps:
      - checkout
      - run: make lint
  test:
    executor: go
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run: make test
      - codecov/upload
      - store_test_results:
          path: results.xml
  load:
    executor: go
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run: make load


workflows:
  version: 2
  ci:
    jobs:
      - lint
      - test
